#!/bin/sh

XORG=working/xorg
EVDEV=working/evdev

mkdir -p $XORG
( 
    cd $XORG
    cat ../../xorg-server-pkg-1.13.1-1.urls | wget -i- 
    # for loop w mv
)
mkdir -p $EVDEV
(
    cd $EVDEV
    cat ../../xf86-input-evdev-2.7.3-2.urls | wget -i-
    # for loop
)
