#!/bin/sh
mkdir -p xorg
( 
    cd xorg
    cat ../xorg-server-pkg-1.13.1-1.urls | wget -i- 
    # for loop w mv
)
mkdir -p evdev
(
    cd evdev
    cat ../xf86-input-evdev-2.7.3-2.urls | wget -i-
    # for loop
)
